var:
  pipelineName: pipeline_serviceA
  gitProvider: Github
  path: harshkumar1/Service-A
  branches: main
  #pipelineName: Service-A-Master
  nodePool: build-nodes
  artifactory: Artifactory
  repo: sign-art-docker-release
  imageName: harsh.jfrogdev.org/sign-art-docker-release/service-a
